authors=[Victor Valentim](https\://victorvalentim.com/)
categories=3D, Video & Vision
library.copyright=(c) 2024 Victor Valentim
library.dependencies=ControlP5, Spout, Syphon
library.keywords=fulldome, projection, immersive, VR, visual, real-time, NDI, Syphon, Spout
maxRevision=0
minRevision=227
name=ziviDomeLive
paragraph=Includes independent Standard and spherical rendering, scene management, projection calibration, and optional NDI, Syphon, or Spout output routing.
prettyVersion=1.5.0
sentence=Facilitates the creation of immersive visual experiences for fulldome projections.
tested.platform=osx,windows,linux
tested.processingVersion=4.5.6
url=https\://github.com/vicvalentim/ziviDomeLive
version=10
