site_name: ziviDomeLive - Processing Library Documentation
site_url: https://vicvalentim.github.io/ziviDomeLive/
repo_url: https://github.com/vicvalentim/ziviDomeLive
repo_name: "GitHub"
edit_uri: "blob/main/docs/"
site_description: "Real-time immersive visuals and 3D rendering framework for fulldome and VR in Processing"
site_author: "Victor Valentim"
copyright: Copyright &copy; 2024  <a href="https://vicvalentim.com/" target="_blank">Victor Valentim</a> - MIT License

theme:
  name: material
  language: en

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer
    - header.autohide

plugins:
  - search
  - offline
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português (Brasil)
          build: true
          site_name: ziviDomeLive - Documentação da Biblioteca Processing
          site_description: "Framework de visualização imersiva em tempo real e renderização 3D para fulldome e VR em Processing"
          nav_translations:
            Home: "Início"
            Installation: "Instalação"
            Requirements: "Requisitos"
            Installation Steps: "Passos de Instalação"
            Dependencies: "Dependências"
            Getting Started: "Introdução"
            Quickstart Guide: "Guia Rápido"
            Key Features: "Funcionalidades Principais"
            Usage: "Uso"
            Basic Usage: "Uso Básico"
            Scene Management: "Gerenciamento de Cenas"
            Event Handling: "Manipulação de Eventos"
            External Integration: "Integração Externa"
            API Reference: "Referência da API"
            Overview: "Visão Geral"
            Core Classes: "Classes Principais"
            Scene Interface: "Interface de Cena"
            Helper Functions: "Funções Auxiliares"
            Examples: "Exemplos"
            Basic Examples: "Exemplos Básicos"
            Advanced Examples: "Exemplos Avançados"
            Contributing: "Contribuindo"
            Known Issues: "Problemas Conhecidos"
            Author: "Autor"
            License: "Licença"

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        [
          "./examples/",
          "./examples/advanced_usage",
          "./examples/getting_started",
        ]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Português (Brasil)
      link: /pt/
      lang: pt

extra_css:
  - assets/extra.css

# Navegação da documentação
nav:
  - Home: index.md
  - Installation:
      - Requirements: installation/requirements.md
      - Installation Steps: installation/installation-steps.md
      - Dependencies: installation/dependencies.md
  - Getting Started:
      - Quickstart Guide: getting-started/quickstart.md
      - Key Features: getting-started/features.md
  - Usage:
      - Basic Usage: usage/basic-usage.md
      - Scene Management: usage/scene-management.md
      - Event Handling: usage/event-handling.md
      - External Integration: usage/external-integration.md
  - API Reference:
      - Overview: api/overview.md
      - Core Classes: api/core-classes.md
      - Scene Interface: api/scene-interface.md
      - Helper Functions: api/helper-functions.md
  - Examples:
      - Basic Examples: examples/basic.md
      - Advanced Examples: examples/advanced.md
  - Contributing: contributing.md
  - Known Issues: known-issues.md
  - Author: author.md
  - License: license.md
