site_name: ziviDomeLive - Processing Library Documentation
site_url: https://vicvalentim.github.io/ziviDomeLive/
repo_url: https://github.com/vicvalentim/ziviDomeLive
repo_name: "GitHub"
edit_uri: "blob/main/docs/"
site_description: "Real-time immersive visuals and 3D rendering framework for fulldome and VR in Processing"
site_author: "Victor Valentim"
copyright: Copyright &copy; 2024  <a href="https://vicvalentim.com/" target="_blank">Victor Valentim</a> - MIT License

theme:
  name: material
  language: en
  font:
    text: Noto Sans
    code: Noto Mono

  favicon: assets/png/favicon.ico
  logo: assets/png/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - navigation.prune
    - toc.follow
    - navigation.footer

  icon:
    repo: fontawesome/brands/github
    search: material/magnify
    close: material/close-circle

plugins:
  - search
  - offline
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português (Brasil)
          build: true
          site_name: ziviDomeLive - Documentação da Biblioteca Processing
          site_description: "Framework de visualização imersiva em tempo real e renderização 3D para fulldome e VR em Processing"
          nav_translations:
            Home: "Início"
            Installation: "Instalação"
            Requirements: "Requisitos"
            Installation Steps: "Passos de Instalação"
            Dependencies: "Dependências"
            Getting Started: "Introdução"
            Quickstart Guide: "Guia Rápido"
            Key Features: "Funcionalidades Principais"
            Usage: "Uso"
            Basic Usage: "Uso Básico"
            Scene Management: "Gerenciamento de Cenas"
            Event Handling: "Manipulação de Eventos"
            External Integration: "Integração Externa"
            API Reference: "Referência da API"
            Overview: "Visão Geral"
            Core Classes: "Classes Principais"
            Scene Interface: "Interface de Cena"
            Helper Functions: "Funções Auxiliares"
            Examples: "Exemplos"
            Basic Examples: "Exemplos Básicos"
            Advanced Examples: "Exemplos Avançados"
            Contributing: "Contribuindo"
            Known Issues: "Problemas Conhecidos"
            Author: "Autor"
            License: "Licença"

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - "./examples/"
        - "./examples/advanced_usage"
        - "./examples/getting_started"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

extra:
  consent:
    title: "Cookie consent"
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
      custom: Custom cookie
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Português (Brasil)
      link: /pt/
      lang: pt
  pt_consent:
    title: "Consentimento de Cookies"
    description: >-
      Utilizamos cookies para reconhecer suas visitas e preferências,
      além de medir a eficácia da nossa documentação. Com seu consentimento,
      você nos ajuda a melhorar nossa documentação.

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/extra.js

# Navegação da documentação
nav:
  - Home: index.md
  - Installation:
      - Requirements: installation/requirements.md
      - Installation Steps: installation/installation-steps.md
      - Dependencies: installation/dependencies.md
  - Getting Started:
      - Quickstart Guide: getting-started/quickstart.md
      - Key Features: getting-started/features.md
  - Usage:
      - Basic Usage: usage/basic-usage.md
      - Scene Management: usage/scene-management.md
      - Event Handling: usage/event-handling.md
      - External Integration: usage/external-integration.md
  - API Reference:
      - Overview: api/overview.md
      - Core Classes: api/core-classes.md
      - Scene Interface: api/scene-interface.md
      - Helper Functions: api/helper-functions.md
  - Examples:
      - Basic Examples: examples/basic.md
      - Advanced Examples: examples/advanced.md
  - Contributing: contributing.md
  - Known Issues: known-issues.md
  - Author: author.md
  - License: license.md
