site_name: ziviDomeLive - Library Documentation
site_url: "https://vicvalentim.github.io/ziviDomeLive/"

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer

copyright: MIT Licence.

plugins:
  - search
  - offline

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Reference:
      - Overview: api/overview.md
      - Classes: api/classes.md
      - Functions: api/functions.md
  - Examples: examples.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md