site_name: ziviDomeLive
site_url: "https://vicvalentim.github.io/ziviDomeLive/"
use_directory_urls: false  # Para documentação offline

theme:
  name: material
  language: en

  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer
    - header.autohide

plugins:
  - search
  - offline
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          default: false
          name: Português (Brasil)
          build: true

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        [
          "./examples/",
          "./examples/advanced_usage",
          "./examples/getting_started",
        ]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

repo_url: https://github.com/vicvalentim/ziviDomeLive
repo_name: "GitHub"
edit_uri: "blob/main/docs/"
site_description: "Real-time immersive visuals and 3D rendering framework for fulldome and VR in Processing"
site_author: "Victor Valentim"
copyright: Copyright &copy; 2024  <a href="https://vicvalentim.com/" target="_blank">Victor Valentim</a> - MIT License

extra:
  alternate:
    - name: English
      link: /ziviDomeLive/en/
      lang: en
    - name: Português (Brasil)
      link: /ziviDomeLive/pt/
      lang: pt

extra_css:
  - assets/extra.css

# Navegação da documentação
nav:
  - en:
      - Home: en/index.md
      - Installation:
          - Requirements: en/installation/requirements.md
          - Installation Steps: en/installation/installation-steps.md
          - Dependencies: en/installation/dependencies.md
      - Getting Started:
          - Quickstart Guide: en/getting-started/quickstart.md
          - Key Features: en/getting-started/features.md
      - Usage:
          - Basic Usage: en/usage/basic-usage.md
          - Scene Management: en/usage/scene-management.md
          - Event Handling: en/usage/event-handling.md
          - External Integration: en/usage/external-integration.md
      - API Reference:
          - Overview: en/api/overview.md
          - Core Classes: en/api/core-classes.md
          - Scene Interface: en/api/scene-interface.md
          - Helper Functions: en/api/helper-functions.md
      - Examples:
          - Basic Examples: en/examples/basic.md
          - Advanced Examples: en/examples/advanced.md
      - Contributing: en/contributing.md
      - Known Issues: en/known-issues.md
      - Author: en/author.md
      - License: en/license.md
  - pt:
      - Home: pt/index.md
      - Instalação:
          - Requisitos: pt/installation/requirements.md
          - Passos de Instalação: pt/installation/installation-steps.md
          - Dependências: pt/installation/dependencies.md
      - Introdução:
          - Guia Rápido: pt/getting-started/quickstart.md
          - Funcionalidades Principais: pt/getting-started/features.md
      - Uso:
          - Uso Básico: pt/usage/basic-usage.md
          - Gerenciamento de Cenas: pt/usage/scene-management.md
          - Manipulação de Eventos: pt/usage/event-handling.md
          - Integração Externa: pt/usage/external-integration.md
      - Referência da API:
          - Visão Geral: pt/api/overview.md
          - Classes Principais: pt/api/core-classes.md
          - Interface de Cena: pt/api/scene-interface.md
          - Funções Auxiliares: pt/api/helper-functions.md
      - Exemplos:
          - Exemplos Básicos: pt/examples/basic.md
          - Exemplos Avançados: pt/examples/advanced.md
      - Contribuindo: pt/contributing.md
      - Problemas Conhecidos: pt/known-issues.md
      - Autor: pt/author.md
      - Licença: pt/license.md
